### ISSUE TITLE
Continuous prediction of action does not result in the desired action.

### ISSUE THREAD

**Issue by realsama** [OuYanghaoyue/gym_contra#2]
I am running into an issue where if my agent predicts the **["right", "B"]** action continuously, the environment only reacts to the **"right"** part and the agent character only runs right without firing his gun.

**Comment by lossv** [comment]
Yes, I also meet the same issue by use   A3C ,but if  you use  DQN  it can word perfectly

**Comment by lossv** [comment]
I take random choose action, it still work

**Comment by realsama** [comment]
Thanks, I figured that out already.
